# Generated by Django 2.2.3 on 2019-07-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'image',
                'managed': False,
            },
        ),
    ]
